### PR TITLE
Educational category added

### PR DESCRIPTION
**Pull request by hpirlo**
we can extend this list by adding good resources for people who want to learn more about embedded systems.

### CODE REVIEW

**Comment by hpirlo** [comment]
I also added Openstlinux to the OS list.

**Comment by iDoka** [comment]
First of all thanks for your contribution.

I'm concerning about including topic about learning matters. This is a quite large topic and deserves a separate list like
 `awesome-embedded-education`.

The same concern about adding linux-based OS: I think this is more of a class of Edge systems, while this list is an attempt to focus on embedded systems that use 8/16/32 bit microcontrollers with tiny resources (RAM/ROM) as the target platform.

**Comment by hpirlo** [comment]
Great idea! I agree with adding another repo for  `awesome-embedded-education`.

**Comment by iDoka** [comment]
I have added details in description sections in order to clarify purpose of list.
Your feedback helps me to do best  
https://github.com/iDoka/awesome-embedded-software/commit/155e3205830c26b26721a9d0129082facb292123

**Pull request closed without merging**
